import { DocsLayout } from "@/layouts/Docs";
import "@workspace/ui/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { Toaster as SonnerToaster } from "sonner";
import { Toaster } from "@workspace/ui/components/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <body
        className={`antialiased text-neutral-800 bg-neutral-50`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
          enableColorScheme
        >
          <DocsLayout tocs={<div id="toc"></div>}>{children}</DocsLayout>
          <SonnerToaster />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
